### ISSUE TITLE
[Bug] ZygiskZygiskOnKernelSU cannot be installed on Bliss OS 14 (Android 11)

### ISSUE THREAD

**Issue by vinphan** [Dr-TSNG/ZygiskNext#49]
### Steps to reproduce/复现步骤

After the installation, the screen is just black after reboot.

### Expected behaviour/预期行为

After the installation, the screen is just black after reboot.

### Actual behaviour/实际行为

After the installation, the screen is just black after reboot.

### KernelSU Module List/KernelSU 模块列表

```Shell
10990
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

v4-0.7.1

### Android version/Android 版本

11

### KernelSU version/KernelSU 版本

10990

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

The screen is just black after reboot, I can't see logs.

**Comment by RashadGasimly** [comment]
do you use magisk overlayfs?

**Comment by johnzxlin** [comment]
> do you use magisk overlayfs?
> 

You mean that magisk overlayfs crashed with zygisk ?

**Comment by Dr-TSNG** [comment]
Try https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/6623678530
