### ISSUE TITLE
[Bug] Zygisk not working on S23+

### ISSUE THREAD

**Issue by trinhdong0005** [Dr-TSNG/ZygiskNext#60]
### Steps to reproduce/复现步骤

1. Install ZygiskNext v4-0.8.1
2. Reboot

### Expected behaviour/预期行为

Zygisk is loaded and works with Shamiko and PlayIntegrityFix

### Actual behaviour/实际行为

Looks like zygisk is not loaded. Shamiko and PlayIntegrityFix not working

### KernelSU Module List/KernelSU 模块列表

```Shell
music-revanced-magisk-v6.22.51-arm64-v8a
gphoto-unlimited-zygisk-v1.1-stable
PlayIntegrityFix_v9.7.3
systemless-hosts-KernelSU-module v1.1.1
youtube-revanced-magisk-v18.38.44-all
LSPosed-v1.9.2-7024-zygisk
Shamiko-v0.7.3-174
Zygisk-Next-v4-0.8.1-111-47e515e-debug
```

### Zygisk Next version/Zygisk Next 版本

v4-0.8.1-111-47e515e

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

11326

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[dumpstate-2023-10-26-11-55-33.zip](https://github.com/Dr-TSNG/ZygiskNext/files/13173074/dumpstate-2023-10-26-11-55-33.zip)
[KernelSU_bugreport_2023-10-26_11_53.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/13173075/KernelSU_bugreport_2023-10-26_11_53.tar.gz)

**Comment by 5ec1cff** [comment]
disable systemless-hosts-KernelSU-module

**Comment by trinhdong0005** [comment]
Thank you. It worked. Problem is systemless-hosts-KernelSU-module
