### ISSUE TITLE
[Feature Request] Android 9/SDK 28 support

### ISSUE THREAD

**Issue by DadiBit** [Dr-TSNG/ZygiskNext#62]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

The "safetynet-fix" module supports android 8-13, but to use it, I need to install this module through KernelSU, which only works on android 10+.

### Describe the solution you'd like/描述你想要的解决方案

Porting Zygisk to older android versions (9 in particular).

### Additional context/其他信息

I'm running stock Android EMUI 9.1 on a Huawei P20 lite (ANE-LX1) with just the bootloader unlocked and enforcing KernelSU.

**Comment by 5ec1cff** [comment]
try https://github.com/Dr-TSNG/ZygiskNext/actions/runs/6754656340

**Comment by hxj827796034** [comment]
安卓9解决了吗？是否支持安装三件套了

**Comment by DadiBit** [comment]
> 安卓9解决了吗？是否支持安装三件套了

Just tested: the `release` module installs fine without complaints. Enabling the "safetynet-fix" module and rebooting a second time doesn't let me pass the safetynet check (CTS profiles do not match). I believe it's an issue with that other module, thus I'm going to close the issue here.
