### ISSUE TITLE
[Bug] Unable to access lspoed 1.9.2 after flashing Zygisk v4-0.8.1

### ISSUE THREAD

**Issue by NotCrissss** [Dr-TSNG/ZygiskNext#65]
### Steps to reproduce/复现步骤

1. Install Zygisk Next v4.-0.8.1 on KernelSU
2. Install lspoed v1.9.2 on kernelsu
3. Reboot the device
4. Tap lspoed and unable to access the app, and no lspoed os running on the notification bar

### Expected behaviour/预期行为

Can access lspoed on the notification bar as expected and use all related xposed apps

### Actual behaviour/实际行为

When tap on the lspoed shortcut, it just crash and unable to access it 
When i reverted back to v4-0.7.0 Zygisk on kernelsu, i can access the lspoed as expected.

### KernelSU Module List/KernelSU 模块列表

```Shell
A1-內存管理 （version 4)
Miui 動態溫控 (version 20230324)
Universal safetynet fix (version v2.4.0-mod_2.0)
Systemless hosts kernelsu module (versionv1.1.1)
Shamiko (version0.7.4)
ZygiskNext (v4-0.8.1)
```

### Zygisk Next version/Zygisk Next 版本

Zygisk-Next-v4-0.8.1-117-8204e67-release.zip

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

V0.7.0 (11326)

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

I am sorry, the log file is about 163 mb, how do i upload the log file as the size limit is 25mb only.
Cam i upload it to other file storage and provide you the url?

I would like to upload the file but i cannot from here.
Please let me know if other alternatives are available.

I want to upload the video of this issue but the size is bigger than 10mb, so please let me know how to upload as well.
I am glad to share it to you.

**Comment by cccClyde** [comment]
I can confirm this issue does exist. Ran into the same situation where LSPosed Manager was not accessible no matter the methods (even with dialer key code). 

And maybe you could try Google Drive for uploading the logs?

**Comment by NotCrissss** [comment]
> I can confirm this issue does exist. Ran into the same situation where LSPosed Manager was not accessible no matter the methods (even with dialer key code).
> 
> And maybe you could try Google Drive for uploading the logs?

Of course, I will upload both the bug replication video and the logs as well for your reference.
- [Bug Replication video](https://drive.google.com/file/d/15PHjJtPunA35aEu6k2-SXqNCi-Mkj_Gf/view?usp=drive_link)
- [KSU logs](https://drive.google.com/file/d/1l1-DNO2fyW-Ybjj8cvMArm0dCFjHvsnE/view?usp=drive_link)

**Comment by 5ec1cff** [comment]
try disable systemless host module

**Comment by NotCrissss** [comment]
Thanks, I'll check it out later
today.
However, these modules work on the older version (Zygisk v4-0.7.1)

**Comment by NotCrissss** [comment]
Thanks, it looks like it is related to systemless host module.
I deactivated the module and it worked fine but it is compatible on the
older version of zygisk on KernelSU (v4-0.7.1).

Can you optimize it?

**Comment by 5ec1cff** [comment]
try this version https://github.com/5ec1cff/ZygiskNext/actions/runs/6841138590

**Comment by cccClyde** [comment]
> try this version https://github.com/5ec1cff/ZygiskNext/actions/runs/6841138590

Works great for me. Thank you!

**Comment by NotCrissss** [comment]
Hi Clyde, but my security app and app permission are broke (keep force
closing) and inaccessible after updating the 126 version.

The systemless host module is working fine

I will upload the ksu log later today
