### ISSUE TITLE
[Feature Request] Support ARM64 only modules on x86_64 emulators

### ISSUE THREAD

**Issue by Yehh22** [Dr-TSNG/ZygiskNext#68]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Most Zygisk based game injection modules, downloaded from platinmods.com and other sites, only work on ARM64 and can't be loaded on x86_64 emulators, regardless if you use Build-in Zygisk or Zygisk Next. Build-in Zygisk also does not load, the error says "Zygisk module not loaded due to incompatibility"

### Describe the solution you'd like/描述你想要的解决方案

Since emulators always have ARM translation, I would like Zygisk Next to use ARM translator in order to load the module. This is my last hope to use game injection modules on emulator

**Comment by 5ec1cff** [comment]
We cannot guarantee that the module will work properly after translation
