### ISSUE TITLE
After copying the certificate to the system, it does not show up in the trust credentials.

### ISSUE THREAD

**Issue by ldhhp** [Dr-TSNG/ZygiskNext#69]
### Steps to reproduce/复现步骤

1:复制的新证书到/system/etc/security/cacerts/目录下，在信任凭据中无法显示出来。证书是成功复制了，且已经权限配置生效。
2:当关闭 zygisknext模块后，证书就可以显示出来。
3:只要打开zygisknext，就无法显示出新证书。 

### Expected behaviour/预期行为

应该能在打开模块的情况下，显示出成功复制的证书

### Actual behaviour/实际行为

在证书复制成功的情况下，打开模块证书就从信任凭据中消失

### KernelSU Module List/KernelSU 模块列表

```Shell
zygisk next
```

### Zygisk Next version/Zygisk Next 版本

4.0.8.1

### Android version/Android 版本

12

### KernelSU version/KernelSU 版本

0.7.1

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

no log

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/ZygiskNext/actions/runs/6852625402
