### ISSUE TITLE
v4-0.8.1 with Shamiko v0.7.4 whitelist mode fool Magisk itself!

### ISSUE THREAD

**Issue by SinhoMoeme** [Dr-TSNG/ZygiskNext#74]
### Steps to reproduce/复现步骤

1.Install Magisk v26.4.
2.Install Shamiko v0.7.4.
3.Create a empty file "/data/adb/shamiko/whitelist" to enter Shamiko whitelist mode.
4.Reboot and run Magisk, it will say "root was lost" or "Installed: N/A".
5.Run a application which need root permission, you will find root didn't truly lost.
6.Delete or rename the "whitelist" file and reboot, Magisk can detect itself again.

### Expected behaviour/预期行为

Magisk can still detect installation of itself after Shamiko installed. (With official Zygisk will behave like that.)

### Actual behaviour/实际行为

Magisk can't detect itself when run Shamiko on Zygisk Next.

### KernelSU Module List/KernelSU 模块列表

```Shell
Shamiko v0.7.4
```

### Zygisk Next version/Zygisk Next 版本

v4-0.8.1

### Android version/Android 版本

12&13&14

### KernelSU version/KernelSU 版本

Magisk v26.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[magisk.log](https://github.com/Dr-TSNG/ZygiskNext/files/13680504/magisk.log)

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/ZygiskNext/commit/d5c896e9667a7efd8455f84ee7975d2948f8bae3
