### ISSUE TITLE
pixel8pro官方系统14.0.0 (UQ1A.231205.015, Dec 2023)+kernel suv0.7.1最新版刷v4-0.8.0可以适配几乎所有模块，v4-0.8.1不可以会导致一堆模块失效，例如pixel xpert

### ISSUE THREAD

**Issue by hongfa1380** [Dr-TSNG/ZygiskNext#75]
### Steps to reproduce/复现步骤

1. 手机重置系统后，刷入boot.img，获得ksu，刷入v4-0.8.1
2. 刷入lsposed，安装pixel xpert 3.2.0或者[Iconify v6.6.0](https://github.com/Mahmud0808/Iconify/releases/tag/v6.6.0)，重启后无效果
3. 刷入v4-0.8.0，重启后，pixel xpert 3.2.0或者[Iconify v6.6.0](https://github.com/Mahmud0808/Iconify/releases/tag/v6.6.0)就能使用
4. 手机重置系统后，刷入boot.img，获得ksu，刷入v4-0.8.0
5. 刷入lsposed，安装pixel xpert 3.2.0或者[Iconify v6.6.0](https://github.com/Mahmud0808/Iconify/releases/tag/v6.6.0)，重启后能正常使用
6. 刷入v4-0.8.1，重启后，pixel xpert 3.2.0和[Iconify v6.6.0](https://github.com/Mahmud0808/Iconify/releases/tag/v6.6.0)不能使用。

### Expected behaviour/预期行为

本来这些模块在面具上都可以使用

### Actual behaviour/实际行为

结果升级到v4-0.8.1和之后所有调试版本，几乎所有模块都不能使用了，应该是支持32位引起的。pixel8pro是纯64位芯片和纯64位系统

### KernelSU Module List/KernelSU 模块列表

```Shell
lconftiy 6.6.0 stable
pixel xpert 3.2.0 stable
lsposed 1.9.2 stable
zygisk next v4-0.8.1
```

### Zygisk Next version/Zygisk Next 版本

zygisk next v4-0.8.1

### Android version/Android 版本

14

### KernelSU version/KernelSU 版本

v0.7.1

### Version requirement/版本要求

- [ ] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-12-21_16_34.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/13739084/KernelSU_bugreport_2023-12-21_16_34.tar.gz)

**Comment by 5ec1cff** [comment]
https://github.com/5ec1cff/ZygiskNext/actions/runs/7270732875

**Comment by hongfa1380** [comment]
> https://github.com/5ec1cff/ZygiskNext/actions/runs/7270732875

都试过了，大佬

**Comment by 5ec1cff** [comment]
何意味

**Comment by hongfa1380** [comment]
> ![image](https://private-user-images.githubusercontent.com/56485584/292149586-bcf5ef72-b9c0-4d49-adc0-d2a89d5192b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDk0NDQsIm5iZiI6MTcwMzE0OTE0NCwicGF0aCI6Ii81NjQ4NTU4NC8yOTIxNDk1ODYtYmNmNWVmNzItYjljMC00ZDQ5LWFkYzAtZDJhODlkNTE5MmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4NTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNzVjMTAyNzc2YjA3MDRjYWY2ZGVlYzRjN2I1ZjU5MDFhNzY0NGY1Mzc2YzFjMWNmNjQ1Yzk5ZmQwY2ExMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YI-xe0goPfiiFCesxQZ7fge4zY2ovboTMfigxyBUI24) 何意味

我现在再刷一次您发的调试版
