### ISSUE TITLE
[Bug] Zygisk Next 无法启动

### ISSUE THREAD

**Issue by FishMagic** [Dr-TSNG/ZygiskNext#78]
### Steps to reproduce/复现步骤

无

### Expected behaviour/预期行为

Zygisk Next正常加载

### Actual behaviour/实际行为

[monitor: stopped (zygote: crashed), zygote64: unknown, daemon64: running ...]

### KernelSU Module List/KernelSU 模块列表

```Shell
Adgurad Certificate
Universal SatetyNet Fix
LSPosed
Shamiko
Storge Isolation
Sui
Zygisk Next
```

### Zygisk Next version/Zygisk Next 版本

v4-0.8.1

### Android version/Android 版本

Android 14

### KernelSU version/KernelSU 版本

11413

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-12-31_18_31.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/13800844/KernelSU_bugreport_2023-12-31_18_31.tar.gz)

**Comment by 5ec1cff** [comment]
升级 storage-isolation 增强模块到 29.0.1
