### ISSUE TITLE
[Bug] Kitsune Mask狐狸面具最新版本使用next最新版本导致lsp失效

### ISSUE THREAD

**Issue by niezigon** [Dr-TSNG/ZygiskNext#81]
### Steps to reproduce/复现步骤

1.安装最新版本Kitsune Mask狐狸面具
2.安装lsp模块
3.关闭面具设置里面的zygisk
4.安装最新版本next 模块
5.重启手机

### Expected behaviour/预期行为

各模块正常工作

### Actual behaviour/实际行为

lsp模块没有工作，没有任何效果（我无法判断其他需要zygisk的模块是否正常工作）

### KernelSU Module List/KernelSU 模块列表

```Shell
zygisk_lsposed
```

### Zygisk Next version/Zygisk Next 版本

v4-0.9.0

### Android version/Android 版本

安卓14

### KernelSU version/KernelSU 版本

Kitsune MaskR6592CA0F-kitsune

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

no

**Comment by niezigon** [comment]
Developer Hello, since I don't have much time to re-update the module version to find the log to send you, but this problem in the versionZygisk-Next-v4-0.8.1-164-cd71452-release
No problem with that.

**Comment by niezigon** [comment]
I am using the Canary version of the Kitsone Masked (Delta Masked). This problem is expected to be noticed by the developers or given a solution，Thank you

**Comment by Dr-TSNG** [comment]
fd603982
