### ISSUE TITLE
KernelSu11425安装v4-0.9.1.1出现Error: Failed to extract assets

### ISSUE THREAD

**Issue by MisakaOne** [Dr-TSNG/ZygiskNext#82]
### Steps to reproduce/复现步骤

![Screenshot_2024-01-05-21-37-15-287_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskNext/assets/108571772/86ae6952-ce06-4c39-8734-4bd4c0bf5325)

### Expected behaviour/预期行为

应该正常安装

### Actual behaviour/实际行为

![Screenshot_2024-01-05-21-37-15-287_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskNext/assets/108571772/3778b9bc-3446-4a3e-83af-cfb502392f88)

### KernelSU Module List/KernelSU 模块列表

```Shell
Zygisk Next
Zygisk-sui
Shamiko
zygisklsposed
```

### Zygisk Next version/Zygisk Next 版本

v4-0.9.1.1

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

v4-0.9.1.1

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[KernelSU_install_log_2024-01-05-21-37-16.log](https://github.com/Dr-TSNG/ZygiskNext/files/13842714/KernelSU_install_log_2024-01-05-21-37-16.log)

**Comment by 5ec1cff** [comment]
https://github.com/tiann/KernelSU/issues/1252

**Comment by 5ec1cff** [comment]
KernelSU 的 bug 已经修复，请更新 manager 到 11426

**Comment by MisakaOne** [comment]
已更新解决
