### ISSUE TITLE
安装了最新的ksu，还是报ksud太旧

### ISSUE THREAD

**Issue by mkcs121** [Dr-TSNG/ZygiskNext#83]
### Steps to reproduce/复现步骤

  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 2.18 MB
e2fsck 1.45.4 (23-Sep-2019)
- Estimated minimum size of the filesystem: 80081
e2fsck 1.45.4 (23-Sep-2019)
- Target image size: 352.62 MB
resize2fs 1.45.4 (23-Sep-2019)
e2fsck 1.45.4 (23-Sep-2019)
- Mounting image
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
*********************
 Zygisk Next 
 by Nullptr, 5ec1cff 
*********************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Installing from KernelSU app
- KernelSU version: 11413 (kernel) + 11413 (ksud)
*********************************************************
! ksud version is too old!
! Please update KernelSU Manager to latest version
*********************************************************
Error: Failed to install module script
- Error: Failed to install module script

### Expected behaviour/预期行为

安装应该没有问题

### Actual behaviour/实际行为

版本误报太旧

### KernelSU Module List/KernelSU 模块列表

```Shell
不适用
```

### Zygisk Next version/Zygisk Next 版本

Zygisk Next-v4-0.9.1.1.zip

### Android version/Android 版本

11

### KernelSU version/KernelSU 版本

11413

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 2.18 MB
e2fsck 1.45.4 (23-Sep-2019)
- Estimated minimum size of the filesystem: 80081
e2fsck 1.45.4 (23-Sep-2019)
- Target image size: 352.62 MB
resize2fs 1.45.4 (23-Sep-2019)
e2fsck 1.45.4 (23-Sep-2019)
- Mounting image
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
*********************
 Zygisk Next 
 by Nullptr, 5ec1cff 
*********************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Installing from KernelSU app
- KernelSU version: 11413 (kernel) + 11413 (ksud)
*********************************************************
! ksud version is too old!
! Please update KernelSU Manager to latest version
*********************************************************
Error: Failed to install module script
- Error: Failed to install module script

**Comment by omer-1080314** [comment]
+1

**Comment by bags432** [comment]
ksu官网最新的release版本才11413，模块要求11425，虽然ksu main分支更新到11427了，但是管理器有签名校验那些，作者大哥兼容下release版本吧

**Comment by ianchb** [comment]
> ksu官网最新的release版本才11413，模块要求11425，虽然ksu main分支更新到11427了，但是管理器有签名校验那些，作者大哥兼容下release版本吧

去KernelSU仓库的Actions，下载新的管理器……

**Comment by scarlettekk** [comment]
When installing the Manager from Actions, it always says Kernelsu not installed? The actual kernel works fine, but the manager app from Actions always says it doesn't work...

**Comment by bags432** [comment]
ksu用了11427，用了release的管理器，我改了模块里面customize.sh的MIN_KSUD_VERSION成功刷进去了，没发现啥问题

**Comment by 5ec1cff** [comment]
https://github.com/tiann/KernelSU/releases/tag/v0.7.5
