### ISSUE TITLE
[Bug] Incorrect minimum ksud version requirement

### ISSUE THREAD

**Issue by zeyudada** [Dr-TSNG/ZygiskNext#84]
### Steps to reproduce/复现步骤

使用KernelSU v0.7.2(11413)刷入v4-0.9.1.1版本的模块时提示ksud version is too old!

### Expected behaviour/预期行为

按流程通过最低版本检测，正确刷入模块

### Actual behaviour/实际行为

KernelSU Manager 最新版是v0.7.2(11413)，但是模块要求KernelSU 11425+.

### KernelSU Module List/KernelSU 模块列表

```Shell
Zygisk Next v4-0.9.1.1
```

### Zygisk Next version/Zygisk Next 版本

v4-0.9.1.1

### Android version/Android 版本

14

### KernelSU version/KernelSU 版本

v0.7.2(11413)

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

没有详细日志

**Comment by Ylarod** [comment]
@zeyudada 666

**Comment by 5ec1cff** [comment]
@zeyudada 666
